version: '3.3'

services:


### MariaDB Container #######################################

    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment: 
            MYSQL_ROOT_PASSWORD: password
  